"""
Core data schemas and Pydantic models for Trust-Aware Service Selection.
Defines formal typed entities for agents, tasks, evidence, verification, and experiments.
"""

from __future__ import annotations

import time
import uuid
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator


class RiskTier(str, Enum):
    """Objective risk stakes tier assigned to a task."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class VerificationMode(str, Enum):
    """Methodology applied to verify task execution outputs."""
    DETERMINISTIC = "DETERMINISTIC"
    SCHEMA = "SCHEMA"
    CONSENSUS = "CONSENSUS"
    HEURISTIC = "HEURISTIC"


class DecisionRecommendation(str, Enum):
    """Recommendation issued by the Trust Evaluation Engine."""
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"
    FALLBACK_CAUTION = "FALLBACK_CAUTION"


class AgentRole(str, Enum):
    """Role occupied by an agent in the ecosystem."""
    CLIENT_ORCHESTRATOR = "CLIENT_ORCHESTRATOR"
    SERVICE_PROVIDER = "SERVICE_PROVIDER"
    VERIFIER_NODE = "VERIFIER_NODE"


class BehaviorClass(str, Enum):
    """Behavioral ground-truth class for simulated agents."""
    RELIABLE = "RELIABLE"
    UNRELIABLE = "UNRELIABLE"
    MALICIOUS = "MALICIOUS"


# 1. Capability Schema
class Capability(BaseModel):
    """Declared capability interface for a service agent."""
    capability_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    domain: str = Field(..., description="Task domain, e.g., 'math_computation', 'code_execution'")
    method_name: str = Field(..., description="Target RPC method or tool function name")
    input_schema: Dict[str, Any] = Field(default_factory=dict, description="JSON Schema for input parameters")
    output_schema: Dict[str, Any] = Field(default_factory=dict, description="JSON Schema for expected output")
    version: str = Field(default="1.0.0")


# 2. Agent Base Schema
class Agent(BaseModel):
    """Base model for an autonomous software agent."""
    agent_id: str = Field(..., description="Unique decentralized identifier or public key hex")
    name: str
    role: AgentRole
    public_key: str
    created_at: int = Field(default_factory=lambda: int(time.time()))


# 3. Service Schema
class Service(Agent):
    """External service agent provider exposing execution endpoints."""
    role: AgentRole = AgentRole.SERVICE_PROVIDER
    endpoint_uri: str
    capabilities: List[Capability] = Field(default_factory=list)
    raw_reputation_score: float = Field(default=0.5, ge=0.0, le=1.0)
    behavior_class: BehaviorClass = BehaviorClass.RELIABLE
    is_reachable: bool = True
    active_sybil_ring: bool = False


# 4. Task Specification Schema
class Task(BaseModel):
    """Specification of work to be delegated."""
    task_id: str = Field(default_factory=lambda: f"task_{uuid.uuid4().hex[:8]}")
    domain: str = Field(..., description="Target domain, e.g., 'code_execution'")
    description: str
    input_payload: Dict[str, Any]
    embedding: Optional[List[float]] = Field(default=None, description="Dense vector embedding of domain/spec")
    risk_level: RiskTier = RiskTier.LOW
    timeout_ms: int = Field(default=2000, gt=0)
    created_at: int = Field(default_factory=lambda: int(time.time()))


# 5. Interaction Schema
class Interaction(BaseModel):
    """Raw execution transaction record between client and service."""
    interaction_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    task_id: str
    service_id: str
    client_id: str
    dispatched_payload: Dict[str, Any]
    returned_payload: Optional[Dict[str, Any]] = None
    latency_ms: float = Field(default=0.0, ge=0.0)
    status_code: int = 200
    timeout_occurred: bool = False
    timestamp: int = Field(default_factory=lambda: int(time.time()))


# 6. Verification Record Schema
class VerificationRecord(BaseModel):
    """Objective validation verdict generated by the Result Verification Layer."""
    verification_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    task_id: str
    service_id: str
    is_success: bool
    rigor_score: float = Field(default=1.0, ge=0.0, le=1.0)
    verification_mode: VerificationMode
    verifier_id: str = "local_sandbox_verifier"
    error_message: Optional[str] = None
    flags: List[str] = Field(default_factory=list)
    execution_time_ms: float = 0.0
    timestamp: int = Field(default_factory=lambda: int(time.time()))
    provenance_hash: str = Field(..., description="SHA-256 hash of task, response, and verdict")


# 7. Evidence Schema (EvidenceRecord)
class Evidence(BaseModel):
    """Permanent empirical evidence record linking interaction to verification."""
    evidence_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    task_id: str
    service_id: str
    task_domain: str
    task_embedding: Optional[List[float]] = None
    risk_level: RiskTier
    latency_ms: float
    is_success: bool
    rigor_score: float = Field(ge=0.0, le=1.0)
    verification_mode: VerificationMode
    provenance_hash: str
    on_chain_commitment_tx: Optional[str] = None
    timestamp: int = Field(default_factory=lambda: int(time.time()))


# 8. Reputation Record Schema
class ReputationRecord(BaseModel):
    """On-chain or registry-reported third-party rating."""
    record_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    service_id: str
    reviewer_id: str
    rating: float = Field(..., ge=0.0, le=1.0)
    is_flagged_sybil: bool = False
    timestamp: int = Field(default_factory=lambda: int(time.time()))


# 9. Risk Assessment Schema
class RiskAssessment(BaseModel):
    """Evaluated stakes and required confidence threshold for a task."""
    task_id: str
    risk_tier: RiskTier
    risk_score: float = Field(..., ge=0.0, le=1.0)
    confidence_threshold: float = Field(..., ge=0.0, le=1.0)
    min_evidence_confidence: float = Field(default=0.4, ge=0.0, le=1.0)
    mandatory_verification_mode: VerificationMode


# 10. Trust Assessment Schema
class TrustAssessment(BaseModel):
    """Multidimensional evaluation of candidate trust for a specific task."""
    candidate_id: str
    task_id: str
    task_domain: str
    expected_success_rate: float = Field(..., ge=0.0, le=1.0)
    evidence_confidence_omega: float = Field(..., ge=0.0, le=1.0)
    evidence_records_evaluated: int = 0
    discounted_reputation: float = Field(..., ge=0.0, le=1.0)
    risk_threshold_required: float = Field(..., ge=0.0, le=1.0)
    recommendation: DecisionRecommendation
    justification: str


# 11. Selection Decision Schema
class SelectionDecision(BaseModel):
    """The final action emitted by the Selection Engine."""
    decision_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    task_id: str
    strategy_used: str
    selected_service_id: Optional[str] = None
    is_rejected: bool = False
    trust_scores_evaluated: Dict[str, float] = Field(default_factory=dict)
    decision_latency_ms: float = 0.0
    timestamp: int = Field(default_factory=lambda: int(time.time()))


# 12. Metric Result Schema
class MetricResult(BaseModel):
    """Computed evaluation metrics for an experimental run."""
    strategy_name: str
    total_tasks: int
    task_success_rate: float = Field(..., ge=0.0, le=1.0)
    malicious_agent_selection_rate: float = Field(..., ge=0.0, le=1.0)
    false_rejection_rate: float = Field(..., ge=0.0, le=1.0)
    avg_verification_cost_ms: float = Field(..., ge=0.0)
    avg_selection_latency_ms: float = Field(..., ge=0.0)


# 13. Experiment Run Schema
class ExperimentRun(BaseModel):
    """Structured telemetry metadata for a complete benchmark run."""
    run_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    scenario_name: str
    seed: int
    population_size: int = 30
    tasks_count: int = 100
    metrics_by_strategy: Dict[str, MetricResult] = Field(default_factory=dict)
    created_at: int = Field(default_factory=lambda: int(time.time()))
